<!-- <button class="btn">Staff Manage</button> -->
<h1>
    <?php echo $block->getIds() ?>
</h1>

<form action="<?= $this->getURL('company/index/form'); ?>" method="post">
    <button type="submit" class="btn">Add Staff</button>  
</form>

<table>
    <tr>
        <th>Entity ID</th>
        <th>Parent ID</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>Created At</th>
        <th>Updated At</th>
        <th>Action</th>
    </tr>
    <?php
        echo $block->showStaffData();
    ?>
</table>

<?php
// echo $block->show();
?>
